import tornado.httpserver
import tornado.ioloop
import tornado.options
import tornado.web
from controllers.violation import Violation as Controller


class Violation(tornado.web.RequestHandler):

    def get(self, *args, **kwargs):
        self.render('Violation.html')

    def post(self, *args, **kwargs):
        id = self.get_argument('id','')
        s_date = self.get_argument('s_date', '')
        m_date = self.get_argument('m_date', '')
        file_no = self.get_argument('file_no', '')
        kootaj = self.get_argument('kootaj', '')
        cert_no = self.get_argument('cert_no', '')
        s_date_1 = self.get_argument('s_date_1', '')
        s_date_2 = self.get_argument('s_date_2', '')
        policy_1 = self.get_argument('policy_1', False)
        policy_2 = self.get_argument('policy_2', False)
        policy_3 = self.get_argument('policy_3', False)
        policy_4 = self.get_argument('policy_4', False)
        policy_5 = self.get_argument('policy_5', False)
        policy_6 = self.get_argument('policy_6', False)
        policy_7 = self.get_argument('policy_7', False)
        ezharname = self.get_argument('ezharname', 0)
        person_type = self.get_argument('person_type', False)
        full_name = self.get_argument('full_name', '')
        card_no = self.get_argument('card_no', '')
        code_no = self.get_argument('code_no', '')
        company = self.get_argument('company', '')
        ez_full_name = self.get_argument('ez_full_name', '')
        ez_owner = self.get_argument('ez_owner', '')
        ez_agent = self.get_argument('ez_agent', '')
        ez_card_no = self.get_argument('ez_card_no', '')
        ez_code_no = self.get_argument('ez_code_no', '')
        tr_full_name = self.get_argument('tr_full_name', '')
        tr_code_no = self.get_argument('tr_code_no', '')
        tr_reg_no = self.get_argument('tr_reg_no', '')
        tr_nationality = self.get_argument('tr_nationality', '')
        tr_manager = self.get_argument('tr_manager', '')
        tr_type = self.get_argument('tr_type', False)
        item_name = self.get_argument('item_name', '')
        tariff_no = self.get_argument('tariff_no', '')
        paid = self.get_argument('paid', 0)
        different = self.get_argument('different', 0)
        fine = self.get_argument('fine', 0)
        diff_paid = self.get_argument('diff_paid', 0)
        vi_type_1 = self.get_argument('vi_type_1', False)
        vi_type_2 = self.get_argument('vi_type_2', False)
        vi_type_3 = self.get_argument('vi_type_3', False)
        vi_type_4 = self.get_argument('vi_type_4', False)
        vi_type_5 = self.get_argument('vi_type_5', False)
        vi_type_6 = self.get_argument('vi_type_6', False)
        vi_type_7 = self.get_argument('vi_type_7', False)
        vi_type_other = self.get_argument('vi_type_other', '')
        stated_tariff = self.get_argument('stated_tariff', 0)
        stated_value = self.get_argument('stated_value', 0)
        stated_weight = self.get_argument('stated_weight', 0)
        deducted_tariff = self.get_argument('deducted_tariff', 0)
        deducted_value = self.get_argument('deducted_value', 0)
        deducted_weight = self.get_argument('deducted_weight', 0)
        law = self.get_argument('law', '')
        detector = self.get_argument('detector', 0)
        detector_other = self.get_argument('detector_other', '')
        results = self.get_argument('results', '')
        commitment = self.get_argument('commitment', False)
        receip_no = self.get_argument('receip_no', '')
        details = self.get_argument('details', '')
        m_rec_date = self.get_argument('m_rec_date', '')
        s_rec_date = self.get_argument('s_rec_date', '')
        locked = self.get_argument('locked', False)

        self.write('s_date:' + str(s_date)+'<br>')
        self.write('m_date:' + str(m_date)+'<br>')
        self.write('file_no:' + str(file_no)+'<br>')
        self.write('kootaj:' + str(kootaj)+'<br>')
        self.write('cert_no:' + str(cert_no)+'<br>')
        self.write('s_date_1:' + str(s_date_1)+'<br>')
        self.write('s_date_2:' + str(s_date_2)+'<br>')
        self.write('policy_1:' + str(policy_1)+'<br>')
        self.write('policy_2:' + str(policy_2)+'<br>')
        self.write('policy_3:' + str(policy_3)+'<br>')
        self.write('policy_4:' + str(policy_4)+'<br>')
        self.write('policy_5:' + str(policy_5)+'<br>')
        self.write('policy_6:' + str(policy_6)+'<br>')
        self.write('policy_7:' + str(policy_7)+'<br>')
        self.write('ezharname:' + str(ezharname)+'<br>')
        self.write('person_type:' + str(person_type)+'<br>')
        self.write('full_name:' + str(full_name)+'<br>')
        self.write('card_no:' + str(card_no)+'<br>')
        self.write('code_no:' + str(code_no)+'<br>')
        self.write('company:' + str(company)+'<br>')
        self.write('ez_full_name:' + str(ez_full_name)+'<br>')
        self.write('ez_owner:' + str(ez_owner)+'<br>')
        self.write('ez_agent:' + str(ez_agent)+'<br>')
        self.write('ez_card_no:' + str(ez_card_no)+'<br>')
        self.write('ez_code_no:' + str(ez_code_no)+'<br>')
        self.write('tr_full_name:' + str(tr_full_name)+'<br>')
        self.write('tr_code_no:' + str(tr_code_no)+'<br>')
        self.write('tr_reg_no:' + str(tr_reg_no)+'<br>')
        self.write('tr_nationality:' + str(tr_nationality)+'<br>')
        self.write('tr_manager:' + str(tr_manager)+'<br>')
        self.write('tr_type:' + str(tr_type)+'<br>')
        self.write('item_name:' + str(item_name)+'<br>')
        self.write('tariff_no:' + str(tariff_no)+'<br>')
        self.write('paid:' + str(paid)+'<br>')
        self.write('different:' + str(different)+'<br>')
        self.write('fine:' + str(fine)+'<br>')
        self.write('diff_paid:' + str(diff_paid)+'<br>')
        self.write('vi_type_1:' + str(vi_type_1)+'<br>')
        self.write('vi_type_2:' + str(vi_type_2)+'<br>')
        self.write('vi_type_3:' + str(vi_type_3)+'<br>')
        self.write('vi_type_4:' + str(vi_type_4)+'<br>')
        self.write('vi_type_5:' + str(vi_type_5)+'<br>')
        self.write('vi_type_6:' + str(vi_type_6)+'<br>')
        self.write('vi_type_7:' + str(vi_type_7)+'<br>')
        self.write('vi_type_other:' + str(vi_type_other)+'<br>')
        self.write('stated_tariff:' + str(stated_tariff)+'<br>')
        self.write('stated_value:' + str(stated_value)+'<br>')
        self.write('stated_weight:' + str(stated_weight)+'<br>')
        self.write('deducted_tariff:' + str(deducted_tariff)+'<br>')
        self.write('deducted_value:' + str(deducted_value)+'<br>')
        self.write('deducted_weight:' + str(deducted_weight)+'<br>')
        self.write('law:' + str(law)+'<br>')
        self.write('detector:' + str(detector)+'<br>')
        self.write('detector_other:' + str(detector_other)+'<br>')
        self.write('results:' + str(results)+'<br>')
        self.write('commitment:' + str(commitment)+'<br>')
        self.write('receip_no:' + str(receip_no)+'<br>')
        self.write('details:' + str(details)+'<br>')
        self.write('m_rec_date:' + str(m_rec_date)+'<br>')
        self.write('s_rec_date:' + str(s_rec_date)+'<br>')
        self.write('locked:' + str(locked)+'<br>')
        # print('ezharname: ' + str(ezharname))
        # print('deducted_tariff: ' + str(deducted_tariff))
        # print('diff_paid: ' + str(diff_paid))
        # print('different: ' + str(different))
        # print('paid: ' + str(paid))
        # print('stated_value: ' + str(stated_value))
        # print('detector: ' + str(detector))
        # print('fine: ' + str(fine))
        # print('stated_tariff: ' + str(stated_tariff))
        # print('deducted_value: ' + str(deducted_value))
        Controller.add(id=id, s_date=s_date, m_date=m_date, file_no=file_no, kootaj=kootaj, cert_no=cert_no, s_date_1=s_date_1, s_date_2=s_date_2, policy_1=policy_1, policy_2=policy_2, policy_3=policy_3, policy_4=policy_4, policy_5=policy_5, policy_6=policy_6, policy_7=policy_7, ezharname=ezharname, person_type=person_type, full_name=full_name, card_no=card_no, code_no=code_no, company=company, ez_full_name=ez_full_name, ez_owner=ez_owner, ez_agent=ez_agent, ez_card_no=ez_card_no, ez_code_no=ez_code_no, tr_full_name=tr_full_name, tr_code_no=tr_code_no, tr_reg_no=tr_reg_no, tr_nationality=tr_nationality, tr_manager=tr_manager, tr_type=tr_type, item_name=item_name, tariff_no=tariff_no, paid=paid, different=different, fine=fine, diff_paid=diff_paid, vi_type_1=vi_type_1, vi_type_2=vi_type_2, vi_type_3=vi_type_3, vi_type_4=vi_type_4, vi_type_5=vi_type_5, vi_type_6=vi_type_6, vi_type_7=vi_type_7, vi_type_other=vi_type_other, stated_tariff=stated_tariff, stated_value=stated_value, stated_weight=stated_weight, deducted_tariff=deducted_tariff, deducted_value=deducted_value, deducted_weight=deducted_weight, law=law, detector=detector, detector_other=detector_other, results=results, commitment=commitment, receip_no=receip_no, details=details, m_rec_date=m_rec_date, s_rec_date=s_rec_date, locked=locked)
