__author__ = 'ehsan'
from mongoengine import *
from connections import *
print(database)
print(mongo_host)
print(mongo_port)
print(mongo_username)
print(mongo_password)
connect(database, host=mongo_host, port=mongo_port, username=mongo_username, password=mongo_password)


class Detect(Document):
    sDate = StringField()
    mDate = DateTimeField()
    FileNo = StringField()
    Kootaj = StringField()
    CertNo = StringField()
    sDate1 = StringField()
    sDate2 = StringField()
    Policy1 = BooleanField()
    Policy2 = BooleanField()
    Policy3 = BooleanField()
    Policy4 = BooleanField()
    Policy5 = BooleanField()
    Policy6 = BooleanField()
    Policy7 = BooleanField()
    Policy8 = BooleanField()
    Ezharname = IntField()
    PersonType = BooleanField()
    FullName = StringField()
    CardNo = StringField()
    CodeNo = StringField()
    Company = StringField()
    EzFullName = StringField()
    EzOwner = StringField()
    EzAgent = StringField()
    EzCardNo = StringField()
    EzCodeNo = StringField()
    TrFullName = StringField()
    TrCodeNo = StringField()
    TrRegNo = StringField()
    TrNationality = StringField()
    TrManager = StringField()
    TrType = BooleanField()
    ItemName = StringField()
    TariffNo = StringField()
    Paid = IntField()
    Different = IntField()
    Fine = IntField()
    DiffPaid = IntField()
    ViType1 = BooleanField()
    ViType2 = BooleanField()
    ViType3 = BooleanField()
    ViType4 = BooleanField()
    ViType5 = BooleanField()
    ViType6 = BooleanField()
    ViType7 = BooleanField()
    ViTypeOther = StringField()
    StatedTariff = IntField()
    StatedValue = IntField()
    StatedWeight = FloatField()
    DeductedTariff = IntField()
    DeductedValue = IntField()
    DeductedWeight = FloatField()
    Law = StringField()
    Detector = IntField()
    DetectorOther = StringField()
    Commitment = BooleanField()
    Results = StringField()
    ReceipNo = StringField()
    Details = StringField()
    Locked = BooleanField()
    mRecDate = DateTimeField()
    sRecDate = StringField()