__author__ = 'ehsan'
from mongoengine import *
from connections import *
connect(database, host=mongo_host, port=mongo_port, username=mongo_username, password=mongo_password)


class Intviolation(Document):
    kootaj = StringField()
    cert_no = StringField()
    s_date = StringField()
    m_date = DateTimeField()
    int_cert_no = StringField()
    radif_marzi = StringField()
    s_entry_date = StringField()
    m_entry_date = DateTimeField()
    karne_tir_no = StringField()
    ezhar_1 = BooleanField()
    ezhar_2 = BooleanField()
    ezhar_3 = BooleanField()
    ezhar_4 = BooleanField()
    person_type = BooleanField()
    full_name = StringField()
    card_no = StringField()
    code_no = StringField()
    dest_address = StringField()
    good_name = StringField()
    net_weight = StringField()
    weight = StringField()
    input_tariff = StringField()
    good_count = IntField()
    price = IntField()
    truck_no = StringField()
    driver_name = StringField()
    chasis_no = StringField()
    trailer_no = StringField()
    iranian_truck = BooleanField()
    truck_address = StringField()
    truck_type = IntField()
    vi_type_1 = BooleanField()
    vi_type_2 = BooleanField()
    vi_type_3 = BooleanField()
    vi_type_4 = BooleanField()
    vi_type_5 = BooleanField()
    vi_type_6 = BooleanField()
    vi_type_7 = BooleanField()
    detector = IntField()
    detector_other = StringField()
    fine_receipt_no = StringField()
    fine_price = IntField()
    final_result = IntField()
    details = StringField()
    m_rec_date = DateTimeField()
    s_rec_date = StringField()
    locked = BooleanField()
