__author__ = 'ehsan'
from mongoengine import *
from connections import *
connect(database, host=mongo_host, port=mongo_port, username=mongo_username, password=mongo_password)
print 'MONGO: ' + mongo_host


class Violation(Document):
    s_date = StringField()
    m_date = DateTimeField()
    file_no = StringField()
    kootaj = StringField()
    cert_no = StringField()
    s_date_1 = StringField()
    s_date_2 = StringField()
    policy_1 = BooleanField()
    policy_2 = BooleanField()
    policy_3 = BooleanField()
    policy_4 = BooleanField()
    policy_5 = BooleanField()
    policy_6 = BooleanField()
    policy_7 = BooleanField()
    ezharname = IntField()
    person_type = BooleanField()
    full_name = StringField()
    card_no = StringField()
    code_no = StringField()
    company = StringField()
    ez_full_name = StringField()
    ez_owner = StringField()
    ez_agent = StringField()
    ez_card_no = StringField()
    ez_code_no = StringField()
    tr_full_name = StringField()
    tr_code_no = StringField()
    tr_reg_no = StringField()
    tr_nationality = StringField()
    tr_manager = StringField()
    tr_type = BooleanField()
    item_name = StringField()
    tariff_no = StringField()
    paid = IntField()
    different = IntField()
    fine = IntField()
    diff_paid = IntField()
    vi_type_1 = BooleanField()
    vi_type_2 = BooleanField()
    vi_type_3 = BooleanField()
    vi_type_4 = BooleanField()
    vi_type_5 = BooleanField()
    vi_type_6 = BooleanField()
    vi_type_7 = BooleanField()
    vi_type_other = StringField()
    stated_tariff = IntField()
    stated_value = IntField()
    stated_weight = IntField()
    deducted_tariff = IntField()
    deducted_value = IntField()
    deducted_weight = IntField()
    law = StringField()
    detector = IntField()
    detector_other = StringField()
    results = StringField()
    commitment = BooleanField()
    receip_no = StringField()
    details = StringField()
    m_rec_date = DateTimeField()
    s_rec_date = StringField()
    locked = BooleanField()
